# Terraform Variables for test101
# Generated by Self-Service Portal
# Request ID: SR-1001
# Requester: Subodh
# Timestamp: 2026-02-05 18:21:18

# Deployment Settings
deployment_name     = "test101"
resource_group_name = "rg-panorama-gitops-poc"
location            = "eastus"
environment         = "dev"

# VM Settings
vm_count        = 2
vm_name_prefix  = "testVM01, testVM02"
vm_size         = "Standard_B2s"
os_type         = "ubuntu_22_04"
admin_username  = "azureadmin"

# Network Settings
vnet_address_space    = "10.0.0.0/16"
subnet_address_prefix = "10.0.1.0/24"
create_public_ip      = true

# NSG Rules
nsg_rules = ["ssh", "rdp", "http"]

# Custom Ports
custom_ports = ""

# Metadata
request_id  = "SR-1001"
requester   = "Subodh"
description = "test101"

# Tags
tags = {
  "Environment" = "dev"
  "Project"     = "test101"
  "ManagedBy"   = "Terraform"
  "RequestId"   = "SR-1001"
  "Requester"   = "Subodh"
}
